# Generated by Django 3.2.3 on 2021-10-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_audio_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='audio_store',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='audio',
            field=models.FileField(default='song.mp3', upload_to='audioFiles'),
        ),
    ]
